# Generated by Django 5.0.6 on 2026-07-13 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_progress_video_watched"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon key used by the frontend BadgeIcon map",
                        max_length=50,
                    ),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("lessons_completed", "Lessons completed"),
                            ("course_completed", "Course completed"),
                            ("perfect_quiz", "Perfect quiz score"),
                            ("path_complete", "Entire learning path complete"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "criteria_value",
                    models.CharField(
                        blank=True,
                        help_text="Threshold (e.g. '1') or course slug for course_completed",
                        max_length=120,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipped",
                    models.BooleanField(
                        default=False,
                        help_text="Shown as the student's profile accent badge",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="learning.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
