# Generated by Django 5.0.6 on 2026-07-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in skill map')),
            ],
            options={
                'verbose_name_plural': 'skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='1=beginner, 2=intermediate, 3=advanced')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Courses that should be completed first', to='courses.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.skill')),
            ],
            options={
                'ordering': ['skill__order', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True, help_text='Markdown lesson content/instructions')),
                ('lesson_type', models.CharField(choices=[('theory', 'Theory'), ('interactive', 'Interactive'), ('sandbox', 'Sandbox Practical'), ('quiz', 'Quiz'), ('agent_lab', 'AI Agent Lab')], default='theory', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
                ('sandbox_config', models.JSONField(blank=True, default=dict, help_text='Docker image, port, startup command for sandbox lessons')),
                ('ai_tutor_prompt', models.TextField(blank=True, help_text='System prompt snippet for the AI tutor on this lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
